sudo: false

language: groovy

jdk:
- oraclejdk7

env:
- GRAILS_VERSION=2.4.4

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
    - master

before_script:
  - mysql -e 'create database festival_test;'

script: grails clean && grails test-app --non-interactive --stacktrace
