sudo: false

language: groovy

jdk:
- openjdk8

branches:
  only:
    - master

before_script:
  - mysql -e 'create database festival_test;'

script: ./grailsw clean && yes | ./grailsw refresh-dependencies && ./grailsw test-app
